require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - app/views/**/*

Metrics/AbcSize:
  Exclude:
    - app/views/**/*

Lint/MissingSuper:
  Exclude:
    - app/views/**/*
